//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/projects/generic_tools/tags/TimeTag.msg.
//

#ifndef __INET_TIMETAG_M_H
#define __INET_TIMETAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class TimeTag;

}  // namespace inet

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace inet {

/**
 * Class generated from <tt>inet/projects/generic_tools/tags/TimeTag.msg:5</tt> by opp_msgtool.
 * <pre>
 * class TimeTag extends TagBase
 * {
 *     double time;
 * }
 * </pre>
 */
class INET_API TimeTag : public ::inet::TagBase
{
  protected:
    double time = 0;

  private:
    void copy(const TimeTag& other);

  protected:
    bool operator==(const TimeTag&) = delete;

  public:
    TimeTag();
    TimeTag(const TimeTag& other);
    virtual ~TimeTag();
    TimeTag& operator=(const TimeTag& other);
    virtual TimeTag *dup() const override {return new TimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getTime() const;
    virtual void setTime(double time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimeTag& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::TimeTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TimeTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_TIMETAG_M_H

